# Generated by Django 5.1.6 on 2025-02-19 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('ProductCategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('rowguid', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('SalesOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('RevisionNumber', models.IntegerField(blank=True, null=True)),
                ('OrderDate', models.DateTimeField(blank=True, null=True)),
                ('DueDate', models.DateTimeField(blank=True, null=True)),
                ('ShipDate', models.DateTimeField(blank=True, null=True)),
                ('Status', models.IntegerField(blank=True, null=True)),
                ('OnlineOrderFlag', models.BooleanField(blank=True, default=False, null=True)),
                ('SalesOrderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('PurchaseOrderNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('AccountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('CustomerID', models.IntegerField(blank=True, null=True)),
                ('SalesPersonID', models.IntegerField(blank=True, null=True)),
                ('BillToAddressID', models.IntegerField(blank=True, null=True)),
                ('ShipToAddressID', models.IntegerField(blank=True, null=True)),
                ('ShipMethodID', models.IntegerField(blank=True, null=True)),
                ('CreditCardID', models.IntegerField(blank=True, null=True)),
                ('CreditCardApprovalCode', models.CharField(blank=True, max_length=50, null=True)),
                ('CurrencyRateID', models.IntegerField(blank=True, null=True)),
                ('SubTotal', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('TaxAmt', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('Freight', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('TotalDue', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
                ('rowguid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Special_Offer',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('SpecialOfferID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
                ('DiscountPct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Type', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('MinQty', models.IntegerField()),
                ('MaxQty', models.IntegerField(blank=True, null=True)),
                ('rowguid', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('TerritoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=50)),
                ('CountryCapital', models.CharField(max_length=50)),
                ('Population', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product_Subcategory',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('ProductSubcategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('rowguid', models.CharField(max_length=50)),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='python_tasks.product_category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('ProductNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('MakeFlag', models.BooleanField(blank=True, default=False, null=True)),
                ('FinishedGoodsFlag', models.BooleanField(blank=True, default=False, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('SafetyStockLevel', models.IntegerField(blank=True, default=0, null=True)),
                ('ReorderPoint', models.IntegerField(blank=True, default=0, null=True)),
                ('StandardCost', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True)),
                ('ListPrice', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True)),
                ('Size', models.IntegerField(blank=True, null=True)),
                ('SizeUnitMeasureCode', models.CharField(blank=True, max_length=50, null=True)),
                ('WeightUnitMeasureCode', models.CharField(blank=True, max_length=50, null=True)),
                ('Weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('DaysToManufacture', models.IntegerField(blank=True, default=0, null=True)),
                ('ProductLine', models.CharField(blank=True, max_length=50, null=True)),
                ('Class', models.CharField(blank=True, max_length=50, null=True)),
                ('Style', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductModelID', models.IntegerField(blank=True, null=True)),
                ('SellStartDate', models.DateTimeField(blank=True, null=True)),
                ('SellEndDate', models.DateTimeField(blank=True, null=True)),
                ('DiscontinuedDate', models.DateTimeField(blank=True, null=True)),
                ('rowguid', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductSubcategoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='python_tasks.product_subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales_Details',
            fields=[
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('SalesOrderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('CarrierTrackingNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('OrderQty', models.IntegerField(blank=True, null=True)),
                ('UnitPrice', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('UnitPriceDiscount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('LineTotal', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('rowguid', models.CharField(blank=True, max_length=50, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='python_tasks.product')),
                ('SalesOrder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='python_tasks.sales')),
                ('SpecialOffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='python_tasks.special_offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='TerritoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='python_tasks.territory'),
        ),
    ]
